/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog;

/**
 *
 * @author Made
 */
import javax.swing.JLabel;
import com.mycompany.tr_pbog.DarkMode.Listener;

public class DaftarKelasPanel extends javax.swing.JPanel implements Listener {

    /**
     * Creates new form DaftarKelasPanel
     */
    public DaftarKelasPanel() {
        initComponents();
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);
        ContentPanel.setOpaque(false);
    }

    @Override
    public void setDarkMode(boolean isDark) {
        for (java.awt.Component card : ContentPanel.getComponents()) {
            if (card instanceof Listener) { // Cek apakah kartu juga 'Listener'
                ((Listener) card).setDarkMode(isDark);
            }
        }
    }
    public void loadDataKelas(String role) {
    ContentPanel.removeAll();
    

    if (role.equals("dosen")) {
        
        // --- INI ADALAH DUMMY DATA ---
        String[][] dummyKelasDosen = {
            {"IF-401-A", "IF-401: Pemrograman Berorientasi Objek (Kelas A)"},
            {"IF-203-B", "IF-203: Struktur Data (Kelas B)"},
            {"IF-505-A", "IF-505: Kecerdasan Buatan (Kelas A)"},
            {"IF-101-C", "IF-101: Algoritma dan Pemrograman (Kelas C)"},
            {"IF-602-A", "IF-602: Proyek Perangkat Lunak (Kelas A)"},
            {"IF-702-B", "IF-702: Pengenalan Teknologi Informasi"},
            {"IF-401-A", "IF-401: Pemrograman Berorientasi Objek (Kelas A)"},
            {"IF-203-B", "IF-203: Struktur Data (Kelas B)"},
            {"IF-505-A", "IF-505: Kecerdasan Buatan (Kelas A)"},
            {"IF-101-C", "IF-101: Algoritma dan Pemrograman (Kelas C)"},
            {"IF-602-A", "IF-602: Proyek Perangkat Lunak (Kelas A)"},
            {"IF-702-B", "IF-702: Pengenalan Teknologi Informasi"}

        };

        for (String[] kelas : dummyKelasDosen) {
            String idKelas = kelas[0];
            String namaKelas = kelas[1];

            // Buat Card baru, kirim ID sama Nama
            DosenKelasCardPanel card = new DosenKelasCardPanel(idKelas, namaKelas);
            
            //Tambah Card ke ContentPanel
            ContentPanel.add(card);
            // --------------------------
        }
        
    } else if (role.equals("mahasiswa")) {
        // WIP COY, belum ada Cardnya
        ContentPanel.add(new JLabel("Tampilan untuk Mahasiswa"));
    }

    ContentPanel.revalidate();
    ContentPanel.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ContentPanel = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        ContentPanel.setOpaque(false);
        ContentPanel.setLayout(new javax.swing.BoxLayout(ContentPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(ContentPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
