/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog;

import com.mycompany.tr_pbog.DarkMode.Listener;

import dbCon.Dosen;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author Made
 */
public class DosenDashboardPanel extends javax.swing.JPanel implements Listener{

    /**
     * Creates new form DosenDashboardPanel
     */
    public DosenDashboardPanel(Dosen dosen) {
        initComponents();
        initDateTime();
        setDarkMode(DarkMode.isDarkMode);
        namaLabel.setText(dosen.getNama());
        nidLabel.setText(dosen.getNid());
    }
       
    @Override
       public void setDarkMode(boolean isDark) {
        
        if(isDark){
            DosenDashboardPanel.setBackground(new Color(38, 38, 40));
            dateLabel.setForeground(Color.WHITE);
            clockLabel.setForeground(Color.WHITE);
            salamLabel.setForeground(Color.WHITE);
            biodataLabel.setForeground(Color.WHITE);
            nidLabel.setForeground(Color.WHITE);
            namaLabel.setForeground(Color.WHITE);
            jLabel1.setForeground(Color.WHITE);
            jLabel2.setForeground(Color.WHITE);
        }else{
            DosenDashboardPanel.setBackground(new Color(249, 248, 246));
            dateLabel.setForeground(Color.BLACK);
            clockLabel.setForeground(Color.BLACK);
            biodataLabel.setForeground(Color.BLACK);
            salamLabel.setForeground(Color.BLACK);
            nidLabel.setForeground(Color.BLACK);
            namaLabel.setForeground(Color.BLACK);
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
        }
       }
    private void initDateTime() {

    // lokalisasi Indonesia
    Locale localeIndonesia = Locale.of("id", "ID");

    //Format terpisah untuk setiap JLabel
    DateTimeFormatter formatTanggal = DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy", localeIndonesia);
    DateTimeFormatter formatJam = DateTimeFormatter.ofPattern("HH:mm:ss");

    //Timer untuk memperbarui semuanya
    Timer timer = new Timer(1000, e -> {
        // Kode berjalan setiap 1 detik
        LocalDateTime now = LocalDateTime.now();

        // Terapkan teks ke label masing-masing
        dateLabel.setText(now.format(formatTanggal));
        clockLabel.setText(now.format(formatJam));
    });
    
    timer.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DosenDashboardPanel = new javax.swing.JPanel();
        salamLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        clockLabel = new javax.swing.JLabel();
        biodataLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        nidLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);

        DosenDashboardPanel.setOpaque(false);

        salamLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salamLabel.setText("Selamat Datang di Sistem Administrasi");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateLabel.setText("dateLabel");
        dateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        clockLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clockLabel.setText("clockLabel");

        biodataLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biodataLabel.setText("Biodata:");

        namaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaLabel.setText("[nama lengkap pengguna]");

        nidLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nidLabel.setText("[NID Pengguna]");

        jLabel1.setText("Nama: ");

        jLabel2.setText("NID:");

        javax.swing.GroupLayout DosenDashboardPanelLayout = new javax.swing.GroupLayout(DosenDashboardPanel);
        DosenDashboardPanel.setLayout(DosenDashboardPanelLayout);
        DosenDashboardPanelLayout.setHorizontalGroup(
            DosenDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DosenDashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DosenDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockLabel)
                    .addComponent(salamLabel)
                    .addComponent(biodataLabel)
                    .addGroup(DosenDashboardPanelLayout.createSequentialGroup()
                        .addGroup(DosenDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DosenDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DosenDashboardPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nidLabel))
                            .addComponent(namaLabel))))
                .addContainerGap(807, Short.MAX_VALUE))
        );
        DosenDashboardPanelLayout.setVerticalGroup(
            DosenDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DosenDashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockLabel)
                .addGap(27, 27, 27)
                .addComponent(salamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biodataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DosenDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DosenDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nidLabel)
                    .addComponent(jLabel2))
                .addContainerGap(453, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DosenDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DosenDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DosenDashboardPanel;
    private javax.swing.JLabel biodataLabel;
    private javax.swing.JLabel clockLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel nidLabel;
    private javax.swing.JLabel salamLabel;
    // End of variables declaration//GEN-END:variables
}
