/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog;

import com.mycompany.tr_pbog.DarkMode.Listener;
import java.awt.Color;

/**
 *
 * @author Made
 */
public class DosenKelasCardPanel extends javax.swing.JPanel implements Listener{

    /**
     * Creates new form DosenKelasCard
     */
    private String classID;
    
    public DosenKelasCardPanel(String classID, String className) {
        initComponents(); 
        setDarkMode(DarkMode.isDarkMode);
        this.classID = classID;
        this.namaKelasLabel.setText(className);
       
        this.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(200, 200, 200)));
    }
    
    @Override
    public void setDarkMode(boolean isDark) {
        Color bgColor = isDark ? new Color(38, 38, 40) : Color.WHITE;
        Color textColor = isDark ? Color.WHITE : Color.BLACK;
        
        this.setBackground(bgColor); 
        this.buttonPanel.setBackground(bgColor);
        this.namaKelasLabel.setForeground(textColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaKelasLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        lihatMhsButton = new javax.swing.JButton();
        inputNilaiButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 60));
        setMinimumSize(new java.awt.Dimension(282, 60));
        setPreferredSize(new java.awt.Dimension(282, 60));
        setLayout(new java.awt.BorderLayout());

        namaKelasLabel.setText("[namaKelas]");
        namaKelasLabel.setToolTipText("");
        add(namaKelasLabel, java.awt.BorderLayout.CENTER);

        buttonPanel.setMaximumSize(new java.awt.Dimension(32767, 23));
        buttonPanel.setPreferredSize(new java.awt.Dimension(212, 23));
        java.awt.GridBagLayout buttonPanelLayout = new java.awt.GridBagLayout();
        buttonPanelLayout.columnWeights = new double[] {1.0};
        buttonPanel.setLayout(buttonPanelLayout);

        lihatMhsButton.setText("Lihat Mahasiswa");
        buttonPanel.add(lihatMhsButton, new java.awt.GridBagConstraints());

        inputNilaiButton.setText("Input Nilai");
        buttonPanel.add(inputNilaiButton, new java.awt.GridBagConstraints());

        add(buttonPanel, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton inputNilaiButton;
    private javax.swing.JButton lihatMhsButton;
    private javax.swing.JLabel namaKelasLabel;
    // End of variables declaration//GEN-END:variables
}
