/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tr_pbog;

import com.mycompany.tr_pbog.DarkMode.Listener;
import java.awt.Color;

/**
 *
 * @author Made
 */
public class inputNilai extends javax.swing.JFrame implements Listener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inputNilai.class.getName());

    /**
     * Creates new form inputNilai
     */
    public inputNilai() {
        initComponents();
        setDarkMode(DarkMode.isDarkMode);
    }
    
    @Override
    public void setDarkMode(boolean isDark) {
        

        if(isDark){
            panelDasar.setBackground(new Color(44, 44, 44));
            headerPanel.setBackground(new Color(44, 44, 44));
            centerPanel.setBackground(new Color(44, 44, 44));
            judulLabel.setForeground(Color.WHITE);
            labelInptNilai.setForeground(Color.WHITE);
//            titik2Username.setForeground(Color.WHITE);
//            titik2Password.setForeground(Color.WHITE);
        }else{
            panelDasar.setBackground(new Color(249, 248, 246));
            headerPanel.setBackground(new Color(249, 248, 246));
            centerPanel.setBackground(new Color(249, 248, 246));
            judulLabel.setForeground(Color.BLACK);
            labelInptNilai.setForeground(Color.BLACK);
//            titik2Username.setForeground(Color.BLACK);
//            titik2Password.setForeground(Color.BLACK);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDasar = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        labelInptNilai = new javax.swing.JLabel();
        inputNilai = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        batalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDasar.setLayout(new java.awt.BorderLayout());

        headerPanel.setLayout(new java.awt.GridBagLayout());

        judulLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        judulLabel.setText("INPUT NILAI");
        headerPanel.add(judulLabel, new java.awt.GridBagConstraints());

        panelDasar.add(headerPanel, java.awt.BorderLayout.NORTH);

        labelInptNilai.setText("Masukkan Nilai: ");

        okBtn.setText("Input");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(batalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(labelInptNilai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInptNilai)
                    .addComponent(inputNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(batalBtn))
                .addGap(17, 17, 17))
        );

        panelDasar.add(centerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelDasar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okBtnActionPerformed

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_batalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inputNilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalBtn;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField inputNilai;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JLabel labelInptNilai;
    private javax.swing.JButton okBtn;
    private javax.swing.JPanel panelDasar;
    // End of variables declaration//GEN-END:variables
}
