/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog;

import com.mycompany.tr_pbog.DarkMode.Listener;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Made
 */
public class kelasDetailCardPanel extends javax.swing.JPanel implements Listener {

    /**
     * Creates new form matkulIndukCardPanel
     */
    private String classID_Detail;

    public kelasDetailCardPanel(String classID, String infoText) {
        initComponents();
        this.classID_Detail = classID;
        this.namaMatkulLabel.setText(infoText);
        
        // Atur warna awal
        setDarkMode(DarkMode.isDarkMode);
        this.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(200, 200, 200)));
    }
    
    // Metode ini kita buat agar AmbilKelasPanel bisa menambahkan listener
    public JButton getAmbilButton() {
        return this.ambilButton;
    }

    @Override
    public void setDarkMode(boolean isDark) {
        Color bgColor = isDark ? new Color(50, 50, 52) : Color.WHITE;
        Color textColor = isDark ? Color.WHITE : Color.BLACK;

        this.setBackground(bgColor);
        this.namaMatkulLabel.setForeground(textColor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaMatkulLabel = new javax.swing.JLabel();
        ambilButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 100));
        setMinimumSize(new java.awt.Dimension(129, 100));
        setPreferredSize(new java.awt.Dimension(400, 100));
        setLayout(new java.awt.BorderLayout());

        namaMatkulLabel.setText("jLabel1");
        add(namaMatkulLabel, java.awt.BorderLayout.CENTER);

        ambilButton.setText("Ambil Kelas");
        ambilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilButtonActionPerformed(evt);
            }
        });
        add(ambilButton, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void ambilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ambilButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambilButton;
    private javax.swing.JLabel namaMatkulLabel;
    // End of variables declaration//GEN-END:variables
}
