/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog;

import com.mycompany.tr_pbog.DarkMode.Listener;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author Made
 */
public class MahasiswaDashboardPanel extends javax.swing.JPanel implements Listener {

    /**
     * Creates new form MahasiswaDashboardPanel
     */
    
    private void initDateTime() {

    // lokalisasi Indonesia
    Locale localeIndonesia = Locale.of("id", "ID");

    //Format terpisah untuk setiap JLabel
    DateTimeFormatter formatTanggal = DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy", localeIndonesia);
    DateTimeFormatter formatJam = DateTimeFormatter.ofPattern("HH:mm:ss");

    //Timer untuk memperbarui semuanya
    Timer timer = new Timer(1000, e -> {
        // Kode berjalan setiap 1 detik
        LocalDateTime now = LocalDateTime.now();

        // Terapkan teks ke label masing-masing
        dateLabel.setText(now.format(formatTanggal));
        clockLabel.setText(now.format(formatJam));
    });
    
    timer.start();
}
    
    public MahasiswaDashboardPanel() {
        initComponents();
        initDateTime();
        setDarkMode(DarkMode.isDarkMode);
    }

    @Override
    public void setDarkMode(boolean isDark) {
        
        if(isDark){
            dateLabel.setForeground(Color.WHITE);
            clockLabel.setForeground(Color.WHITE);
            salamLabel.setForeground(Color.WHITE);
            biodataLabel.setForeground(Color.WHITE);
            prodiLabel.setForeground(Color.WHITE);
            namaLabel.setForeground(Color.WHITE);
            nimLabel.setForeground(Color.WHITE);
            totalSKSLabel.setForeground(Color.WHITE);
        }else{
            dateLabel.setForeground(Color.BLACK);
            clockLabel.setForeground(Color.BLACK);
            biodataLabel.setForeground(Color.BLACK);
            salamLabel.setForeground(Color.BLACK);
            prodiLabel.setForeground(Color.BLACK);
            namaLabel.setForeground(Color.BLACK);
            nimLabel.setForeground(Color.BLACK);
            totalSKSLabel.setForeground(Color.BLACK);
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalSKSLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        clockLabel = new javax.swing.JLabel();
        salamLabel = new javax.swing.JLabel();
        biodataLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        prodiLabel = new javax.swing.JLabel();

        setOpaque(false);

        totalSKSLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalSKSLabel.setText("Total SKS: [SKS Pengguna]");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateLabel.setText("dateLabel");
        dateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        clockLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clockLabel.setText("clockLabel");

        salamLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salamLabel.setText("Selamat Datang di Sistem Administrasi");

        biodataLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biodataLabel.setText("Biodata:");

        namaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaLabel.setText("Nama: [nama lengkap pengguna]");

        nimLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nimLabel.setText("NIM: [NIM Pengguna]");

        prodiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prodiLabel.setText("Prodi: [Prodi Pengguna]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(biodataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalSKSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 711, Short.MAX_VALUE))
                    .addComponent(salamLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockLabel)
                .addGap(27, 27, 27)
                .addComponent(salamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biodataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalSKSLabel)
                .addContainerGap(401, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biodataLabel;
    private javax.swing.JLabel clockLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JLabel prodiLabel;
    private javax.swing.JLabel salamLabel;
    private javax.swing.JLabel totalSKSLabel;
    // End of variables declaration//GEN-END:variables
}
