/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog;

import com.mycompany.tr_pbog.DarkMode.Listener;
import java.util.List;
import dbCon.Mahasiswa;
import logic.FiturMahasiswa;
import DTO.TranskripNilai;
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Made
 */
public class MahasiswaTranskripNilai extends javax.swing.JPanel implements Listener {

    /**
     * Creates new form TranskripNilaiPanel
     */
    public MahasiswaTranskripNilai(Mahasiswa mhs) {
        initComponents();
        loadTranskrip(mhs);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);
        
        setDarkMode(DarkMode.isDarkMode);
    }
    
    public void loadTranskrip(Mahasiswa mhs) {
        FiturMahasiswa fMahasiswa = new FiturMahasiswa();
        List<TranskripNilai> lsNilai = fMahasiswa.getTranskripNilaiByMahasiswa(mhs);
        String[] columnNames = {"No", "Kode", "Matakuliah", "Nilai"};
    int jumlahMatkul = lsNilai.size();
    Object[][] data = new Object[jumlahMatkul][4];

    for (int i = 0; i < jumlahMatkul; i++) {
        TranskripNilai nilai = lsNilai.get(i);
        
        data[i][0] = (i + 1) + "."; // Nomor urut
        data[i][1] = nilai.getIdKelas(); // Kode kelas
        data[i][2] = nilai.getNamaKelas();
        data[i][3] = nilai.getNilaiAkhir();
    }
        
        // --- TERAPKAN MODEL KE TABEL ---
        DefaultTableModel model = new DefaultTableModel(data, columnNames) {
           @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        
        transkripTable.setModel(model);
        
        // --- ATUR TAMPILAN TABEL ---
        transkripTable.setRowHeight(25);
        transkripTable.getTableHeader().setReorderingAllowed(false);
        transkripTable.getTableHeader().setResizingAllowed(false);
        
        // Atur lebar kolom
        transkripTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        javax.swing.table.TableColumnModel cm = transkripTable.getColumnModel();
        cm.getColumn(0).setPreferredWidth(30);  // No
        cm.getColumn(1).setPreferredWidth(100);  // Kode
        cm.getColumn(2).setPreferredWidth(750); // Matakuliah
        cm.getColumn(3).setPreferredWidth(200);  // Nilai
        
        // Tampilkan tabel di scroll pane
        jScrollPane1.setViewportView(transkripTable);
    }
    
    @Override
    public void setDarkMode(boolean isDark){
         // Tentukan warna
       transkripTable.setShowGrid(true);
       if(isDark == true){
           this.setBackground(new Color(38, 38, 40));
           jScrollPane1.getViewport().setBackground(new Color(38, 38, 40));
           judulLabel.setForeground(Color.WHITE);
           transkripTable.setBackground(new Color(38, 38, 40));
           transkripTable.setForeground(Color.WHITE);
           transkripTable.setGridColor(Color.WHITE);
       }else{
           this.setBackground(new Color(249, 248, 246));
           jScrollPane1.getViewport().setBackground(new Color(249, 248, 246));
           judulLabel.setForeground(Color.BLACK);
           transkripTable.setBackground(new Color(249, 248, 246));
           transkripTable.setForeground(Color.BLACK);
           transkripTable.setGridColor(Color.BLACK);           
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transkripTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        judulLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("TRANSKRIP NILAI");
        add(judulLabel, java.awt.BorderLayout.PAGE_START);

        transkripTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(transkripTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTable transkripTable;
    // End of variables declaration//GEN-END:variables
}
