package com.mycompany.tr_pbog;

import java.awt.Color;
import javax.swing.JFrame;

public class MahasiswaHomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MahasiswaHomePage.class.getName());

    /**
     * Creates new form DosenHomePage
     */
    
private void setButtonIcon(javax.swing.JButton button, String path, int width, int height) {
    try {

        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(getClass().getResource(path));

        // Ubah ukuran ikon
        java.awt.Image originalImage = originalIcon.getImage();
        java.awt.Image resizedImage = originalImage.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);

        // menampilkan ikon baru yang sudah di-resize
        button.setIcon(new javax.swing.ImageIcon(resizedImage));
        
    } catch (Exception e) {
        System.err.println("Error loading icon: " + path);
        // Biarkan tombolnya tanpa ikon jika gambar tidak ditemukan
    }
}
    public MahasiswaHomePage() {
        initComponents();
        setDarkMode(DarkMode.isDarkMode);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setButtonIcon(dashboardBtn, "/image/dashboard.png", 24, 24);
        setButtonIcon(classBtn, "/image/teaching.png", 24, 24);
        setButtonIcon(jadwalBtn, "/image/calendar.png", 24, 24);
        setButtonIcon(nilaiBtn, "/image/exam.png", 24, 24);
        dashboardBtnActionPerformed(null);

    }
    

    
    private void setDarkMode(boolean isDark) {
        
        if(isDark){
            BackPanel.setBackground(new Color(38, 38, 40));
            headerPanel.setBackground(new Color(50, 50, 52));
            mainPanel.setBackground(new Color(38, 38, 40));
            sidebarPanel.setBackground(new Color(50, 50, 52));
            navTitlePanel.setBackground(new Color(50, 50, 52));
            sidebarMenuPanel.setBackground(new Color(50, 50, 52));
            navTitle.setForeground(Color.WHITE);
            mainPanel.setForeground(Color.WHITE);
        }else{
            BackPanel.setBackground(new Color(249, 248, 246));
            headerPanel.setBackground(new Color(217, 207, 199));
            mainPanel.setBackground(new Color(249, 248, 246));
            sidebarPanel.setBackground(new Color(239, 233, 227));
            navTitlePanel.setBackground(new Color(239, 233, 227));
            sidebarMenuPanel.setBackground(new Color(239, 233, 227));
            navTitle.setForeground(Color.BLACK);
            mainPanel.setForeground(Color.BLACK);
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        siasatLogo = new com.mycompany.tr_pbog.ScalableIconLabel();
        sidebarPanel = new javax.swing.JPanel();
        navTitlePanel = new javax.swing.JPanel();
        navTitle = new javax.swing.JLabel();
        sidebarMenuPanel = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        classBtn = new javax.swing.JButton();
        jadwalBtn = new javax.swing.JButton();
        nilaiBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        darkModeToggle = new javax.swing.JToggleButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(204, 255, 204));

        siasatLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/siasat.png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(siasatLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1101, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(siasatLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        BackPanel.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        sidebarPanel.setBackground(new java.awt.Color(0, 255, 255));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 338));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        navTitlePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        navTitlePanel.setOpaque(false);
        navTitlePanel.setPreferredSize(new java.awt.Dimension(200, 50));

        navTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        navTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navTitle.setText("Navigation");

        javax.swing.GroupLayout navTitlePanelLayout = new javax.swing.GroupLayout(navTitlePanel);
        navTitlePanel.setLayout(navTitlePanelLayout);
        navTitlePanelLayout.setHorizontalGroup(
            navTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navTitlePanelLayout.setVerticalGroup(
            navTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarPanel.add(navTitlePanel, java.awt.BorderLayout.PAGE_START);

        sidebarMenuPanel.setPreferredSize(new java.awt.Dimension(200, 100));

        dashboardBtn.setText("Dashboard");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        classBtn.setText("Ambil Kelas");
        classBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classBtnActionPerformed(evt);
            }
        });

        jadwalBtn.setText("Jadwal Kuliah");
        jadwalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalBtnActionPerformed(evt);
            }
        });

        nilaiBtn.setText("Transkrip Nilai");
        nilaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        darkModeToggle.setText("Dark Mode");
        darkModeToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarMenuPanelLayout = new javax.swing.GroupLayout(sidebarMenuPanel);
        sidebarMenuPanel.setLayout(sidebarMenuPanelLayout);
        sidebarMenuPanelLayout.setHorizontalGroup(
            sidebarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(classBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jadwalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nilaiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(sidebarMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(darkModeToggle))
        );
        sidebarMenuPanelLayout.setVerticalGroup(
            sidebarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarMenuPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(classBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jadwalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(nilaiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(darkModeToggle)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        sidebarPanel.add(sidebarMenuPanel, java.awt.BorderLayout.CENTER);

        BackPanel.add(sidebarPanel, java.awt.BorderLayout.WEST);

        mainPanel.setBackground(new java.awt.Color(51, 255, 51));
        mainPanel.setLayout(new java.awt.BorderLayout());
        BackPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    
    private void classBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classBtnActionPerformed

    private void darkModeToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeToggleActionPerformed
        // TODO add your handling code here:
        setDarkMode(darkModeToggle.isSelected());
        DarkMode.isDarkMode = darkModeToggle.isSelected();

        if (darkModeToggle.isSelected()) {
            darkModeToggle.setText("Light Mode");
        } else {
            darkModeToggle.setText("Dark Mode");
        }
        if (mainPanel.getComponentCount() > 0) {
            
            // Ambil panel yang sedang aktif
            java.awt.Component activePanel = mainPanel.getComponent(0);
            
            // Cek apakah panel itu mendengarkan
            if (activePanel instanceof DarkMode.Listener) {
                
                // Panggil fungsi setDarkMode() milik panel aktif itu!
                ((DarkMode.Listener) activePanel).setDarkMode(darkModeToggle.isSelected());
            }
        }
    }//GEN-LAST:event_darkModeToggleActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new MahasiswaDashboardPanel(), java.awt.BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void jadwalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalBtnActionPerformed
        // TODO add your handling code here:
        // 1. Buat panel daftar (yang SAMA persis)
        DaftarKelasPanel panelJadwal = new DaftarKelasPanel();

        // 2. Muat data, tapi dengan role "mahasiswa"
        panelJadwal.loadDataKelas("mahasiswa"); 

        // 3. Tampilkan di mainPanel
        mainPanel.removeAll();
        mainPanel.add(panelJadwal, java.awt.BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_jadwalBtnActionPerformed

    private void nilaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        loginPage login = new loginPage();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MahasiswaHomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JButton classBtn;
    private javax.swing.JToggleButton darkModeToggle;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jadwalBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel navTitle;
    private javax.swing.JPanel navTitlePanel;
    private javax.swing.JButton nilaiBtn;
    private javax.swing.JLabel siasatLogo;
    private javax.swing.JPanel sidebarMenuPanel;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
