/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog;

import com.mycompany.tr_pbog.DarkMode.Listener;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Made
 */
public class MahasiswaNilaiCardPanel extends javax.swing.JPanel implements Listener {

    private String studentID;
    private boolean isEditing = false; // Status untuk melacak mode edit
    private Border defaultTextFieldBorder; // Menyimpan border asli
    /**
     * Creates new form MahasiswaNilaiCardPanel
     */
    public MahasiswaNilaiCardPanel(String studentID, String studentName, String initialNilai) {
        initComponents();
        this.studentID = studentID;
        this.namaMahasiswaLabel.setText(studentID + " - " + studentName);
        
        if (initialNilai == null || initialNilai.isEmpty() || initialNilai.equals("-")) {
            this.nilaiField.setText("-");
        } else {
            this.nilaiField.setText(initialNilai);
        }
        
        // Simpan border default (yang null/No Border)
        this.defaultTextFieldBorder = this.nilaiField.getBorder();
        
        // Atur UI awal
        setEditing(false); // Mode awal (read-only)
        setDarkMode(DarkMode.isDarkMode);
    }
        
        private void setEditing(boolean editing) {
            this.isEditing = editing;

            if (editing) {
                // --- MASUK MODE EDIT ---
                nilaiField.setEditable(true);
                // Beri border agar terlihat aktif
                nilaiField.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1)); 
                nilaiField.requestFocusInWindow(); // Pindahkan kursor ke sini
                nilaiField.selectAll(); // Pilih semua teks
                editButton.setText("OK");
            } else {
                // --- KELUAR MODE EDIT (READ-ONLY) ---
                nilaiField.setEditable(false);
                nilaiField.setBorder(defaultTextFieldBorder); // Kembalikan border
                editButton.setText("Input Nilai");

                // TODO: Di sini Anda akan menyimpan nilaiField.getText() ke database
                // menggunakan this.studentID dan ID Kelas
                System.out.println("Simpan Nilai: " + nilaiField.getText() + " untuk MHS: " + this.studentID);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        namaMahasiswaLabel = new javax.swing.JLabel();
        nilaiPanel = new javax.swing.JPanel();
        nilaiLabel = new javax.swing.JLabel();
        nilaiField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        infoPanel.setAlignmentX(0.0F);
        infoPanel.setLayout(new javax.swing.BoxLayout(infoPanel, javax.swing.BoxLayout.Y_AXIS));

        namaMahasiswaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaMahasiswaLabel.setText("jLabel1");
        infoPanel.add(namaMahasiswaLabel);

        nilaiPanel.setAlignmentX(0.0F);
        nilaiPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nilaiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nilaiLabel.setText("Nilai: ");
        nilaiPanel.add(nilaiLabel);

        nilaiField.setEditable(false);
        nilaiField.setColumns(5);
        nilaiField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nilaiField.setText("-");
        nilaiField.setBorder(null);
        nilaiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiFieldActionPerformed(evt);
            }
        });
        nilaiPanel.add(nilaiField);

        infoPanel.add(nilaiPanel);

        add(infoPanel, java.awt.BorderLayout.CENTER);

        editButton.setText("jButton1");
        editButton.setPreferredSize(new java.awt.Dimension(120, 23));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        add(editButton, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setDarkMode(boolean isDark) {
        // Tentukan warna
        Color bgColor = isDark ? new Color(50, 50, 52) : Color.WHITE;
        Color textColor = isDark ? Color.WHITE : Color.BLACK;
        Color fieldBg = isDark ? new Color(60, 60, 60) : new Color(240, 240, 240);

        this.setBackground(bgColor);
        this.infoPanel.setBackground(bgColor);
        this.nilaiPanel.setBackground(bgColor);
        
        this.namaMahasiswaLabel.setForeground(textColor);
        this.nilaiLabel.setForeground(textColor);
        
        // Atur warna text field
        this.nilaiField.setBackground(fieldBg);
        this.nilaiField.setForeground(textColor);
        // Atur warna kursor (caret)
        this.nilaiField.setCaretColor(textColor); 
    }
    
    private void nilaiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiFieldActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        setEditing(!this.isEditing);
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel namaMahasiswaLabel;
    private javax.swing.JTextField nilaiField;
    private javax.swing.JLabel nilaiLabel;
    private javax.swing.JPanel nilaiPanel;
    // End of variables declaration//GEN-END:variables
}
