/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog.mahasiswa;

import com.mycompany.tr_pbog.DarkMode;
import com.mycompany.tr_pbog.DarkMode.Listener;

import dbCon.Mahasiswa;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author Made
 */
public class MahasiswaDashboardPanel extends javax.swing.JPanel implements Listener {

    /**
     * Creates new form MahasiswaDashboardPanel
     */
    
    private void initDateTime() {
    Locale localeIndonesia = Locale.of("id", "ID");
    DateTimeFormatter formatTanggal = DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy", localeIndonesia);
    DateTimeFormatter formatJam = DateTimeFormatter.ofPattern("HH:mm:ss");
    Timer timer = new Timer(1000, e -> {
        LocalDateTime now = LocalDateTime.now();
        dateLabel.setText(now.format(formatTanggal));
        clockLabel.setText(now.format(formatJam));
    });
    
    timer.start();
}
    
    public MahasiswaDashboardPanel(Mahasiswa mhs) {
        String namaMhs = mhs.getNama();
        String nim = mhs.getNim();
        float ipk = mhs.getIpk();
        initComponents();
        namaLabel.setText(namaMhs);
        nimLabel.setText(nim);
        totalIPKLabel.setText(Float.toString(ipk));
        initDateTime();
        setDarkMode(DarkMode.isDarkMode);
    }

    @Override
    public void setDarkMode(boolean isDark) {
        
        if(isDark){
            dateLabel.setForeground(Color.WHITE);
            clockLabel.setForeground(Color.WHITE);
            salamLabel.setForeground(Color.WHITE);
            biodataLabel.setForeground(Color.WHITE);
            nama.setForeground(Color.WHITE);
            nim.setForeground(Color.WHITE);
            IPK.setForeground(Color.WHITE);
            namaLabel.setForeground(Color.WHITE);
            nimLabel.setForeground(Color.WHITE);
            totalIPKLabel.setForeground(Color.WHITE);
        }else{
            dateLabel.setForeground(Color.BLACK);
            clockLabel.setForeground(Color.BLACK);
            biodataLabel.setForeground(Color.BLACK);
            salamLabel.setForeground(Color.BLACK);
            nama.setForeground(Color.BLACK);
            nim.setForeground(Color.BLACK);
            IPK.setForeground(Color.BLACK);
            namaLabel.setForeground(Color.BLACK);
            nimLabel.setForeground(Color.BLACK);
            totalIPKLabel.setForeground(Color.BLACK);
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalIPKLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        clockLabel = new javax.swing.JLabel();
        salamLabel = new javax.swing.JLabel();
        biodataLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        nim = new javax.swing.JLabel();
        IPK = new javax.swing.JLabel();

        setOpaque(false);

        totalIPKLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalIPKLabel.setText("[IPK Pengguna]");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateLabel.setText("dateLabel");
        dateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        clockLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clockLabel.setText("clockLabel");

        salamLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salamLabel.setText("Selamat Datang di Sistem Administrasi");

        biodataLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biodataLabel.setText("Biodata:");

        namaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaLabel.setText("[nama lengkap pengguna]");

        nimLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nimLabel.setText("[NIM Pengguna]");

        nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nama.setText("Nama: ");

        nim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nim.setText("NIM: ");

        IPK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IPK.setText("Total IPK: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salamLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(biodataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IPK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalIPKLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockLabel)
                .addGap(27, 27, 27)
                .addComponent(salamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biodataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimLabel)
                    .addComponent(nim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalIPKLabel)
                    .addComponent(IPK))
                .addContainerGap(427, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IPK;
    private javax.swing.JLabel biodataLabel;
    private javax.swing.JLabel clockLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel nim;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JLabel salamLabel;
    private javax.swing.JLabel totalIPKLabel;
    // End of variables declaration//GEN-END:variables
}
