/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog.mahasiswa;

import com.mycompany.tr_pbog.DarkMode;
import com.mycompany.tr_pbog.DarkMode.Listener;
import com.mycompany.tr_pbog.dosen.inputNilai;
import java.awt.Color;
import javax.swing.border.Border;

/**
 *
 * @author Made
 */
public class MahasiswaNilaiCardPanel extends javax.swing.JPanel implements Listener {

    private String studentID;
    private String idKelas;

    public MahasiswaNilaiCardPanel(String studentID, String studentName, String idKelas) {
        initComponents();
        this.idKelas = idKelas;
        this.studentID = studentID;
        this.namaMahasiswaLabel.setText(studentID + " - " + studentName);
        setDarkMode(DarkMode.isDarkMode);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        namaMahasiswaLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(400, 50));
        setLayout(new java.awt.BorderLayout());

        infoPanel.setAlignmentX(0.0F);
        infoPanel.setOpaque(false);
        infoPanel.setLayout(new java.awt.BorderLayout());

        namaMahasiswaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaMahasiswaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaMahasiswaLabel.setText("jLabel1");
        namaMahasiswaLabel.setAlignmentY(0.0F);
        namaMahasiswaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        infoPanel.add(namaMahasiswaLabel, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.BorderLayout());
        add(infoPanel, java.awt.BorderLayout.CENTER);
        java.awt.Dimension fixedSize = new java.awt.Dimension(2147483647, 80);
        setMaximumSize(fixedSize);
        setMinimumSize(new java.awt.Dimension(300, 80));
        setPreferredSize(new java.awt.Dimension(500, 80));

        editButton.setText("Input Nilai");
        editButton.setPreferredSize(new java.awt.Dimension(120, 23));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        add(editButton, java.awt.BorderLayout.EAST);

        getAccessibleContext().setAccessibleName("nilai");
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setDarkMode(boolean isDark) {
        Color bgColor = isDark ? new Color(50, 50, 52) : Color.WHITE;
        Color textColor = isDark ? Color.WHITE : Color.BLACK;
        
        this.setBackground(bgColor);
        this.infoPanel.setBackground(bgColor);
        
        this.namaMahasiswaLabel.setForeground(textColor);
    }
    
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        inputNilai inpt = new inputNilai(this.studentID, this.idKelas);
        inpt.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel namaMahasiswaLabel;
    // End of variables declaration//GEN-END:variables
}
