/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog.admin;

import com.mycompany.tr_pbog.DarkMode;
import com.mycompany.tr_pbog.DarkMode.Listener;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import dbCon.Matkul;
import repo.MatkulRepository;

/**
 *
 * @author Made
 */
public class AdminMatkulPanel extends javax.swing.JPanel implements Listener {

    /**
     * Creates new form AdminMatkulPanel
     */
    public AdminMatkulPanel() {
        initComponents();
        initTableSize();
        initDateTime();
        jScrollPane1.getViewport().setOpaque(false);
        setDarkMode(DarkMode.isDarkMode);
        loadMatkulData();
    }

    private void loadMatkulData() {
        MatkulRepository matkulRepo = new MatkulRepository();
        List<Matkul> listMatkul = matkulRepo.getAllMatkul();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear existing data

        int no = 1;
        for (Matkul matkul : listMatkul) {
            Object[] row = {
                no++,
                matkul.getId_matkul(),
                matkul.getNama_matkul(),
                matkul.getId_prodi(),
                matkul.getSks(),
                null // Aksi column
            };
            model.addRow(row);
        }
    }

    private void refreshTable() {
        loadMatkulData();
    }

    private void initTableSize(){
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        javax.swing.table.TableColumnModel cm = jTable2.getColumnModel();
        cm.getColumn(0).setPreferredWidth(30);  // No
        cm.getColumn(1).setPreferredWidth(150);  // ID Mata Kuliah
        cm.getColumn(2).setPreferredWidth(380); // Nama Mata Kuliah
        cm.getColumn(3).setPreferredWidth(100);  // Prodi
        cm.getColumn(4).setPreferredWidth(80);  // SKS
        cm.getColumn(5).setPreferredWidth(120); // Aksi
    }

    private void initDateTime() {
        // lokalisasi Indonesia
        Locale localeIndonesia = Locale.of("id", "ID");

        DateTimeFormatter formatTanggal = DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy", localeIndonesia);
        DateTimeFormatter formatJam = DateTimeFormatter.ofPattern("HH:mm:ss");

        //Timer untuk refresh
        Timer timer = new Timer(1000, e -> {
            LocalDateTime now = LocalDateTime.now();

            dateLabel.setText(now.format(formatTanggal));
            clockLabel.setText(now.format(formatJam));
        });

        timer.start();
    }

    @Override
    public void setDarkMode(boolean isDark){
        if (isDark) {
            //dark mode
            jPanel2.setBackground(new Color(38, 38, 40));
            jPanel3.setForeground(Color.WHITE);
            cariMatkulLabel.setForeground(Color.WHITE);
            jTable2.setBackground(new Color(38, 38, 40));
            jTable2.setGridColor(Color.WHITE);
            jTable2.setForeground(Color.WHITE);
            dateLabel.setForeground(Color.WHITE);
            clockLabel.setForeground(Color.WHITE);
            informationTitle.setForeground(Color.WHITE);
        } else {
            // light mode
            jPanel2.setBackground(new Color(249, 248, 246));
            cariMatkulLabel.setForeground(Color.BLACK);
            jTable2.setBackground(new Color(249, 248, 246));
            jTable2.setGridColor(Color.BLACK);
            jTable2.setForeground(Color.BLACK);
            dateLabel.setForeground(Color.BLACK);
            clockLabel.setForeground(Color.BLACK);
            informationTitle.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        clockLabel = new javax.swing.JLabel();
        informationTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tambahButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        cariMatkulLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        cariButton = new javax.swing.JButton();

        setOpaque(false);

        jPanel2.setOpaque(false);

        jPanel4.setOpaque(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Mata Kuliah", "Nama Mata Kuliah", "Prodi", "SKS", "Aksi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setOpaque(false);

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dateLabel.setText("dateLabel");

        clockLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clockLabel.setText("clockLabel");

        informationTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        informationTitle.setText("Data Mata Kuliah");

        jPanel3.setOpaque(false);

        tambahButton.setBackground(new java.awt.Color(0, 204, 0));
        tambahButton.setText("Tambah Mata Kuliah");
        tambahButton.setActionCommand("tambahMatkul");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(0, 0, 255));
        editButton.setText("Edit Mata Kuliah");
        editButton.setActionCommand("editMatkul");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(255, 0, 0));
        hapusButton.setText("Hapus Mata Kuliah");
        hapusButton.setActionCommand("hapusMatkul");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(tambahButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tambahButton)
                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cariMatkulLabel.setText("Cari Mata Kuliah :");

        jTextField1.setText("Cari Nama");
        jTextField1.setActionCommand("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        cariButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cariButton.setText("🔎");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(informationTitle)
                        .addGap(245, 245, 245))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cariMatkulLabel)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(952, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(informationTitle)
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cariMatkulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cariButton)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dateLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(clockLabel)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // Input dialog untuk menambah mata kuliah
        String idMatkul = JOptionPane.showInputDialog(this, "Masukkan ID Mata Kuliah:", "Tambah Mata Kuliah", JOptionPane.PLAIN_MESSAGE);
        if (idMatkul == null || idMatkul.trim().isEmpty()) return;

        String namaMatkul = JOptionPane.showInputDialog(this, "Masukkan Nama Mata Kuliah:", "Tambah Mata Kuliah", JOptionPane.PLAIN_MESSAGE);
        if (namaMatkul == null || namaMatkul.trim().isEmpty()) return;

        // Dropdown pilihan prodi
        String[] prodiOptions = {
            "TI067 - S1 Teknik Informatika",
            "DKV069 - Desain Komunikasi Visual",
            "SI068 - Sistem Informasi",
            "BD084 - Bisnis Digital",
            "D3TI056 - D3 Teknik Informatika",
            "PR059 - Public Relations"
        };
        String selectedProdi = (String) JOptionPane.showInputDialog(
            this,
            "Pilih Program Studi:",
            "Tambah Mata Kuliah",
            JOptionPane.QUESTION_MESSAGE,
            null,
            prodiOptions,
            prodiOptions[0]
        );

        if (selectedProdi == null) {
            return;
        }

        // Extract ID Prodi
        String idProdi = selectedProdi.split(" - ")[0];

        String sksStr = JOptionPane.showInputDialog(this, "Masukkan SKS:", "Tambah Mata Kuliah", JOptionPane.PLAIN_MESSAGE);
        if (sksStr == null || sksStr.trim().isEmpty()) return;

        try {
            int sks = Integer.parseInt(sksStr.trim());

            if (sks < 1 || sks > 6) {
                JOptionPane.showMessageDialog(this, "SKS harus antara 1-6!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            MatkulRepository matkulRepo = new MatkulRepository();
            Matkul matkul = new Matkul(idMatkul.trim(), namaMatkul.trim(), idProdi.trim(), sks);

            if (matkulRepo.createMatkul(matkul)) {
                JOptionPane.showMessageDialog(this, "Mata kuliah berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menambahkan mata kuliah!\n\nKemungkinan penyebab:\n" +
                    "1. ID Mata Kuliah sudah terdaftar\n" +
                    "2. ID Prodi tidak valid\n" +
                    "3. Koneksi database bermasalah\n\n" +
                    "Silakan cek console untuk detail error.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "SKS harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Search on Enter
        cariButtonActionPerformed(evt);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Combo box action
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        String keyword = jTextField1.getText().trim().toLowerCase();

        if (keyword.isEmpty() || keyword.equals("cari nama")) {
            loadMatkulData();
            return;
        }

        MatkulRepository matkulRepo = new MatkulRepository();
        List<Matkul> listMatkul = matkulRepo.getAllMatkul();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        int no = 1;
        for (Matkul matkul : listMatkul) {
            if (matkul.getId_matkul().toLowerCase().contains(keyword) ||
                matkul.getNama_matkul().toLowerCase().contains(keyword) ||
                matkul.getId_prodi().toLowerCase().contains(keyword)) {

                Object[] row = {
                    no++,
                    matkul.getId_matkul(),
                    matkul.getNama_matkul(),
                    matkul.getId_prodi(),
                    matkul.getSks(),
                    null
                };
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_cariButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih mata kuliah yang akan diedit!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idMatkul = jTable2.getValueAt(selectedRow, 1).toString();
        String namaLama = jTable2.getValueAt(selectedRow, 2).toString();
        String prodiLama = jTable2.getValueAt(selectedRow, 3).toString();
        String sksLama = jTable2.getValueAt(selectedRow, 4).toString();

        String namaBaru = JOptionPane.showInputDialog(this, "Masukkan Nama Mata Kuliah Baru:", namaLama);
        if (namaBaru == null || namaBaru.trim().isEmpty()) return;

        // Dropdown pilihan prodi
        String[] prodiOptions = {
            "TI067 - S1 Teknik Informatika",
            "DKV069 - Desain Komunikasi Visual",
            "SI068 - Sistem Informasi",
            "BD084 - Bisnis Digital",
            "D3TI056 - D3 Teknik Informatika",
            "PR059 - Public Relations"
        };

        // Find index of current prodi
        int selectedIndex = 0;
        for (int i = 0; i < prodiOptions.length; i++) {
            if (prodiOptions[i].startsWith(prodiLama)) {
                selectedIndex = i;
                break;
            }
        }

        String selectedProdi = (String) JOptionPane.showInputDialog(
            this,
            "Pilih Program Studi:",
            "Edit Mata Kuliah",
            JOptionPane.QUESTION_MESSAGE,
            null,
            prodiOptions,
            prodiOptions[selectedIndex]
        );

        if (selectedProdi == null) return;
        String prodiBaru = selectedProdi.split(" - ")[0];

        String sksStr = JOptionPane.showInputDialog(this, "Masukkan SKS Baru:", sksLama);
        if (sksStr == null || sksStr.trim().isEmpty()) return;

        try {
            int sks = Integer.parseInt(sksStr.trim());

            if (sks < 1 || sks > 6) {
                JOptionPane.showMessageDialog(this, "SKS harus antara 1-6!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            MatkulRepository matkulRepo = new MatkulRepository();
            Matkul matkul = new Matkul(idMatkul, namaBaru.trim(), prodiBaru.trim(), sks);

            if (matkulRepo.updateMatkul(matkul)) {
                JOptionPane.showMessageDialog(this, "Mata kuliah berhasil diupdate!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengupdate mata kuliah!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "SKS harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih mata kuliah yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idMatkul = jTable2.getValueAt(selectedRow, 1).toString();
        String namaMatkul = jTable2.getValueAt(selectedRow, 2).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus mata kuliah:\n" + namaMatkul + " (" + idMatkul + ")?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            MatkulRepository matkulRepo = new MatkulRepository();
            if (matkulRepo.deleteMatkul(idMatkul)) {
                JOptionPane.showMessageDialog(this, "Mata kuliah berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus mata kuliah!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_hapusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariButton;
    private javax.swing.JLabel cariMatkulLabel;
    private javax.swing.JLabel clockLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel informationTitle;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables
}
