/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog.admin;

import com.mycompany.tr_pbog.DarkMode;
import com.mycompany.tr_pbog.DarkMode.Listener;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import dbCon.Mahasiswa;
import repo.MahasiswaRepository;

/**
 *
 * @author Made
 */
public class AdminMahasiswaPanel extends javax.swing.JPanel implements Listener{

    /**
     * Creates new form AdminMahasiswaPanel
     */
    public AdminMahasiswaPanel() {
        initComponents();
        initTableSize();
        initDateTime();
        jScrollPane1.getViewport().setOpaque(false);
        setDarkMode(DarkMode.isDarkMode);
        loadMahasiswaData();
    }

    private void loadMahasiswaData() {
        MahasiswaRepository mhsRepo = new MahasiswaRepository();
        List<Mahasiswa> listMahasiswa = mhsRepo.getAllMahasiswa();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear existing data

        int no = 1;
        for (Mahasiswa mhs : listMahasiswa) {
            Object[] row = {
                no++,
                mhs.getNim(),
                mhs.getNama(),
                mhs.getNim() + "@student.uksw.edu", // Email generated from NIM
                mhs.getId_prodi(),
                "Aktif",
            };
            model.addRow(row);
        }
    }

    private void refreshTable() {
        loadMahasiswaData();
    }

    private void initTableSize(){
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        javax.swing.table.TableColumnModel cm = jTable2.getColumnModel();
        cm.getColumn(0).setPreferredWidth(30);  // No
        cm.getColumn(1).setPreferredWidth(100);  // NIM
        cm.getColumn(2).setPreferredWidth(331); // Nama Mahasiswa
        cm.getColumn(3).setPreferredWidth(250);  // Email
        cm.getColumn(4).setPreferredWidth(100);  // Progdi
        cm.getColumn(5).setPreferredWidth(140); // Status
    }
    
    private void initDateTime() {
        // lokalisasi Indonesia
        Locale localeIndonesia = Locale.of("id", "ID");
        DateTimeFormatter formatTanggal = DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy", localeIndonesia);
        DateTimeFormatter formatJam = DateTimeFormatter.ofPattern("HH:mm:ss");
        Timer timer = new Timer(1000, e -> {
            LocalDateTime now = LocalDateTime.now();
            dateLabel.setText(now.format(formatTanggal));
            clockLabel.setText(now.format(formatJam));
        });

        timer.start();
    }
    
    @Override
    public void setDarkMode(boolean isDark) {
        if (isDark) {
            jPanel2.setBackground(new Color(38, 38, 40));
            jPanel3.setForeground(Color.WHITE);
            cariDosenLabel.setForeground(Color.WHITE);
            jTable2.setBackground(new Color(38, 38, 40));
            jTable2.setGridColor(Color.WHITE);
            jTable2.setForeground(Color.WHITE);
            dateLabel.setForeground(Color.WHITE);
            clockLabel.setForeground(Color.WHITE);
            informationTitle.setForeground(Color.WHITE);
        } else {
            jPanel2.setBackground(new Color(249, 248, 246));
            cariDosenLabel.setForeground(Color.BLACK);
            jTable2.setBackground(new Color(249, 248, 246));
            jTable2.setGridColor(Color.BLACK);
            jTable2.setForeground(Color.BLACK);
            dateLabel.setForeground(Color.BLACK);
            clockLabel.setForeground(Color.BLACK);
            informationTitle.setForeground(Color.BLACK);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        clockLabel = new javax.swing.JLabel();
        informationTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tambahButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        cariDosenLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        cariButton = new javax.swing.JButton();

        setOpaque(false);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setToolTipText("");
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setOpaque(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "672024125", "William Prasetyo", "672024125@student.uksw.edu", "S1 TI", "Aktif"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "NIM", "Mahasiswa", "Email", "Program Studi", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setShowGrid(true);
        jScrollPane1.setViewportView(jTable2);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setOpaque(false);

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateLabel.setText("dateLabel");
        dateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        clockLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clockLabel.setText("clockLabel");

        informationTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        informationTitle.setText("Data Mahasiswa");

        jPanel3.setOpaque(false);

        tambahButton.setBackground(new java.awt.Color(0, 204, 0));
        tambahButton.setText("Tambah Mahasiswa");
        tambahButton.setActionCommand("tambahDosen");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(0, 0, 255));
        editButton.setText("Edit Mahasiswa");
        editButton.setActionCommand("editDosen");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(255, 0, 0));
        hapusButton.setText("Hapus Mahasiswa");
        hapusButton.setActionCommand("hapusDosen");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(tambahButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tambahButton)
                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cariDosenLabel.setText("Cari Mahasiswa :");

        jTextField1.setText("Cari Nama");
        jTextField1.setActionCommand("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 TI", "DKV", "SI", "BD" }));
        jComboBox1.setActionCommand("List");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        cariButton.setBackground(new java.awt.Color(0, 0, 255));
        cariButton.setText("Cari");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(informationTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cariDosenLabel)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(952, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(informationTitle)
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariDosenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dateLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(clockLabel)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // Input dialog untuk menambah mahasiswa
        String nim = JOptionPane.showInputDialog(this, "Masukkan NIM Mahasiswa:", "Tambah Mahasiswa", JOptionPane.PLAIN_MESSAGE);
        if (nim == null || nim.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIM tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nama = JOptionPane.showInputDialog(this, "Masukkan Nama Mahasiswa:", "Tambah Mahasiswa", JOptionPane.PLAIN_MESSAGE);
        if (nama == null || nama.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Dropdown pilihan prodi
        String[] prodiOptions = {
            "TI067 - S1 Teknik Informatika",
            "DKV069 - Desain Komunikasi Visual",
            "SI068 - Sistem Informasi",
            "BD084 - Bisnis Digital",
            "D3TI056 - D3 Teknik Informatika",
            "PR059 - Public Relations"
        };
        String selectedProdi = (String) JOptionPane.showInputDialog(
            this,
            "Pilih Program Studi:",
            "Tambah Mahasiswa",
            JOptionPane.QUESTION_MESSAGE,
            null,
            prodiOptions,
            prodiOptions[0]
        );

        if (selectedProdi == null) {
            return;
        }

        // Extract ID Prodi (ambil bagian sebelum " - ")
        String idProdi = selectedProdi.split(" - ")[0];

        String ipkStr = JOptionPane.showInputDialog(this, "Masukkan IPK (0.0 - 4.0):", "Tambah Mahasiswa", JOptionPane.PLAIN_MESSAGE);
        if (ipkStr == null || ipkStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "IPK tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sksStr = JOptionPane.showInputDialog(this, "Masukkan Total SKS:", "Tambah Mahasiswa", JOptionPane.PLAIN_MESSAGE);
        if (sksStr == null || sksStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Total SKS tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String password = JOptionPane.showInputDialog(this, "Masukkan Password:", "Tambah Mahasiswa", JOptionPane.PLAIN_MESSAGE);
        if (password == null || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            float ipk = Float.parseFloat(ipkStr.trim());
            int totalSks = Integer.parseInt(sksStr.trim());

            if (ipk < 0 || ipk > 4.0) {
                JOptionPane.showMessageDialog(this, "IPK harus antara 0.0 - 4.0!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            MahasiswaRepository mhsRepo = new MahasiswaRepository();
            Mahasiswa mahasiswa = new Mahasiswa(nim.trim(), nama.trim(), idProdi.trim(), ipk, totalSks);

            if (mhsRepo.createMahasiswa(mahasiswa, password)) {
                JOptionPane.showMessageDialog(this, "Mahasiswa berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menambahkan mahasiswa!\n\nKemungkinan penyebab:\n" +
                    "1. NIM sudah terdaftar\n" +
                    "2. ID Prodi tidak valid\n" +
                    "3. Koneksi database bermasalah\n\n" +
                    "Silakan cek console untuk detail error.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "IPK atau SKS tidak valid! Pastikan format angka benar.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Search on Enter
        cariButtonActionPerformed(evt);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Combo box action
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        String keyword = jTextField1.getText().trim().toLowerCase();

        if (keyword.isEmpty() || keyword.equals("cari nama")) {
            loadMahasiswaData();
            return;
        }

        MahasiswaRepository mhsRepo = new MahasiswaRepository();
        List<Mahasiswa> listMahasiswa = mhsRepo.getAllMahasiswa();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        int no = 1;
        for (Mahasiswa mhs : listMahasiswa) {
            if (mhs.getNim().toLowerCase().contains(keyword) ||
                mhs.getNama().toLowerCase().contains(keyword) ||
                mhs.getId_prodi().toLowerCase().contains(keyword)) {

                Object[] row = {
                    no++,
                    mhs.getNim(),
                    mhs.getNama(),
                    mhs.getNim() + "@student.uksw.edu",
                    mhs.getId_prodi(),
                    "Aktif",
                };
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_cariButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih mahasiswa yang akan diedit!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nim = jTable2.getValueAt(selectedRow, 1).toString();
        String namaLama = jTable2.getValueAt(selectedRow, 2).toString();
        String prodiLama = jTable2.getValueAt(selectedRow, 4).toString();

        String namaBaru = JOptionPane.showInputDialog(this, "Masukkan Nama Baru:", namaLama);
        if (namaBaru == null || namaBaru.trim().isEmpty()) return;

        // Dropdown pilihan prodi
        String[] prodiOptions = {
            "TI067 - S1 Teknik Informatika",
            "DKV069 - Desain Komunikasi Visual",
            "SI068 - Sistem Informasi",
            "BD084 - Bisnis Digital",
            "D3TI056 - D3 Teknik Informatika",
            "PR059 - Public Relations"
        };

        // Find index of current prodi
        int selectedIndex = 0;
        for (int i = 0; i < prodiOptions.length; i++) {
            if (prodiOptions[i].startsWith(prodiLama)) {
                selectedIndex = i;
                break;
            }
        }

        String selectedProdi = (String) JOptionPane.showInputDialog(
            this,
            "Pilih Program Studi:",
            "Edit Mahasiswa",
            JOptionPane.QUESTION_MESSAGE,
            null,
            prodiOptions,
            prodiOptions[selectedIndex]
        );

        if (selectedProdi == null) return;
        String prodiBaru = selectedProdi.split(" - ")[0];

        String ipkStr = JOptionPane.showInputDialog(this, "Masukkan IPK Baru (0.0 - 4.0):", "0.0");
        if (ipkStr == null || ipkStr.trim().isEmpty()) return;

        String sksStr = JOptionPane.showInputDialog(this, "Masukkan Total SKS Baru:", "0");
        if (sksStr == null || sksStr.trim().isEmpty()) return;

        try {
            float ipk = Float.parseFloat(ipkStr.trim());
            int totalSks = Integer.parseInt(sksStr.trim());

            if (ipk < 0 || ipk > 4.0) {
                JOptionPane.showMessageDialog(this, "IPK harus antara 0.0 - 4.0!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            MahasiswaRepository mhsRepo = new MahasiswaRepository();
            Mahasiswa mahasiswa = new Mahasiswa(nim, namaBaru.trim(), prodiBaru.trim(), ipk, totalSks);

            if (mhsRepo.updateMahasiswa(mahasiswa)) {
                JOptionPane.showMessageDialog(this, "Mahasiswa berhasil diupdate!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengupdate mahasiswa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "IPK atau SKS tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih mahasiswa yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nim = jTable2.getValueAt(selectedRow, 1).toString();
        String nama = jTable2.getValueAt(selectedRow, 2).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus mahasiswa:\n" + nama + " (" + nim + ")?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            MahasiswaRepository mhsRepo = new MahasiswaRepository();
            if (mhsRepo.deleteMahasiswa(nim)) {
                JOptionPane.showMessageDialog(this, "Mahasiswa berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus mahasiswa!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_hapusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariButton;
    private javax.swing.JLabel cariDosenLabel;
    private javax.swing.JLabel clockLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel informationTitle;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables
}
