/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tr_pbog.admin;

import com.mycompany.tr_pbog.DarkMode;
import com.mycompany.tr_pbog.DarkMode.Listener;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import repo.DosenRepository;
import repo.MahasiswaRepository;
import repo.MatkulRepository;

/**
 *
 * @author Made
 */
public class AdminDashboard extends javax.swing.JPanel implements Listener {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setDarkMode(DarkMode.isDarkMode);
        initDateTime();
        loadStatistics();
    }

    private void loadStatistics() {
        DosenRepository dosenRepo = new DosenRepository();
        MahasiswaRepository mhsRepo = new MahasiswaRepository();
        MatkulRepository matkulRepo = new MatkulRepository();

        int totalDosen = dosenRepo.getTotalDosen();
        int totalMahasiswa = mhsRepo.getTotalMahasiswa();
        int totalMatkul = matkulRepo.getTotalMatkul();

        jumlahDosen.setText(String.valueOf(totalDosen));
        jumlahMahasiswa.setText(String.valueOf(totalMahasiswa));
        jumlahKelas.setText(String.valueOf(totalMatkul));
    }
    private void initDateTime() {
        // lokalisasi Indonesia
        Locale localeIndonesia = Locale.of("id", "ID");

        DateTimeFormatter formatTanggal = DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy", localeIndonesia);
        DateTimeFormatter formatJam = DateTimeFormatter.ofPattern("HH:mm:ss");

        //Timer untuk refresh
        Timer timer = new Timer(1000, e -> {
            LocalDateTime now = LocalDateTime.now();

            dateLabel.setText(now.format(formatTanggal));
            clockLabel.setText(now.format(formatJam));
        });

        timer.start();
    }
    
    @Override
    public void setDarkMode(boolean isDark) {
        
        if(isDark){
            informationPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE));
            dateLabel.setForeground(Color.WHITE);
            clockLabel.setForeground(Color.WHITE);
            informationTitle.setForeground(Color.WHITE);
            jumlahDosenTitle.setForeground(Color.WHITE);
            jumlahMahasiswaTitle.setForeground(Color.WHITE);
            jumlahKelasTitle.setForeground(Color.WHITE);
            jumlahDosen.setForeground(Color.WHITE);
            jumlahMahasiswa.setForeground(Color.WHITE);
            jumlahKelas.setForeground(Color.WHITE);
            jumlahDosenPanel.setBackground(new Color(50, 50, 52));
            jumlahMahasiswaPanel.setBackground(new Color(50, 50, 52));
            jumlahKelasPanel.setBackground(new Color(50, 50, 52));
            jalanPintasTitle.setForeground(Color.WHITE);
        }else{
            informationPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
            dateLabel.setForeground(Color.BLACK);
            clockLabel.setForeground(Color.BLACK);
            informationTitle.setForeground(Color.BLACK);
            jumlahDosenTitle.setForeground(Color.BLACK);
            jumlahMahasiswaTitle.setForeground(Color.BLACK);
            jumlahKelasTitle.setForeground(Color.BLACK);
            jumlahDosen.setForeground(Color.BLACK);
            jumlahMahasiswa.setForeground(Color.BLACK);
            jumlahKelas.setForeground(Color.BLACK);
            jumlahDosenPanel.setBackground(new Color(239, 233, 227));
            jumlahMahasiswaPanel.setBackground(new Color(239, 233, 227));
            jumlahKelasPanel.setBackground(new Color(239, 233, 227));
            jalanPintasTitle.setForeground(Color.BLACK);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        informationPanel = new javax.swing.JPanel();
        informationTitle = new javax.swing.JLabel();
        jumlahDosenPanel = new javax.swing.JPanel();
        jumlahDosenTitle = new javax.swing.JLabel();
        jumlahDosen = new javax.swing.JLabel();
        jumlahMahasiswaPanel = new javax.swing.JPanel();
        jumlahMahasiswaTitle = new javax.swing.JLabel();
        jumlahMahasiswa = new javax.swing.JLabel();
        jumlahKelasPanel = new javax.swing.JPanel();
        jumlahKelasTitle = new javax.swing.JLabel();
        jumlahKelas = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        clockLabel = new javax.swing.JLabel();
        jalanPintasTitle = new javax.swing.JLabel();
        shortcut1 = new javax.swing.JButton();
        shortcut2 = new javax.swing.JButton();
        shortcut3 = new javax.swing.JButton();

        setOpaque(false);

        dashboardPanel.setBackground(new java.awt.Color(51, 255, 51));
        dashboardPanel.setOpaque(false);

        informationPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        informationPanel.setOpaque(false);

        informationTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        informationTitle.setText("Informasi Universitas");

        jumlahDosenPanel.setBackground(new java.awt.Color(255, 255, 0));
        jumlahDosenPanel.setPreferredSize(new java.awt.Dimension(155, 95));

        jumlahDosenTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlahDosenTitle.setText("Dosen Aktif");

        jumlahDosen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlahDosen.setText("[Jumlah Dosen]");

        javax.swing.GroupLayout jumlahDosenPanelLayout = new javax.swing.GroupLayout(jumlahDosenPanel);
        jumlahDosenPanel.setLayout(jumlahDosenPanelLayout);
        jumlahDosenPanelLayout.setHorizontalGroup(
            jumlahDosenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahDosenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jumlahDosenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahDosenTitle)
                    .addComponent(jumlahDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jumlahDosenPanelLayout.setVerticalGroup(
            jumlahDosenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahDosenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahDosenTitle)
                .addGap(18, 18, 18)
                .addComponent(jumlahDosen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jumlahMahasiswaPanel.setBackground(new java.awt.Color(255, 255, 0));
        jumlahMahasiswaPanel.setPreferredSize(new java.awt.Dimension(155, 95));

        jumlahMahasiswaTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlahMahasiswaTitle.setText("Mahasiswa Aktif");

        jumlahMahasiswa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlahMahasiswa.setText("[Jumlah Mahasiswa]");

        javax.swing.GroupLayout jumlahMahasiswaPanelLayout = new javax.swing.GroupLayout(jumlahMahasiswaPanel);
        jumlahMahasiswaPanel.setLayout(jumlahMahasiswaPanelLayout);
        jumlahMahasiswaPanelLayout.setHorizontalGroup(
            jumlahMahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahMahasiswaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jumlahMahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahMahasiswaTitle)
                    .addComponent(jumlahMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jumlahMahasiswaPanelLayout.setVerticalGroup(
            jumlahMahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahMahasiswaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahMahasiswaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jumlahMahasiswa)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jumlahKelasPanel.setBackground(new java.awt.Color(255, 255, 0));
        jumlahKelasPanel.setPreferredSize(new java.awt.Dimension(155, 0));

        jumlahKelasTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlahKelasTitle.setText("Matkul Semester Ini");

        jumlahKelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlahKelas.setText("[Jumlah Matkul]");

        javax.swing.GroupLayout jumlahKelasPanelLayout = new javax.swing.GroupLayout(jumlahKelasPanel);
        jumlahKelasPanel.setLayout(jumlahKelasPanelLayout);
        jumlahKelasPanelLayout.setHorizontalGroup(
            jumlahKelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahKelasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jumlahKelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahKelasTitle)
                    .addComponent(jumlahKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jumlahKelasPanelLayout.setVerticalGroup(
            jumlahKelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahKelasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahKelasTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jumlahKelas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout informationPanelLayout = new javax.swing.GroupLayout(informationPanel);
        informationPanel.setLayout(informationPanelLayout);
        informationPanelLayout.setHorizontalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(informationPanelLayout.createSequentialGroup()
                        .addComponent(jumlahDosenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jumlahMahasiswaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jumlahKelasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(573, Short.MAX_VALUE))
        );
        informationPanelLayout.setVerticalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informationTitle)
                .addGap(24, 24, 24)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahKelasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationPanelLayout.createSequentialGroup()
                        .addComponent(jumlahMahasiswaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jumlahDosenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateLabel.setText("dateLabel");
        dateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        clockLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clockLabel.setText("clockLabel");

        jalanPintasTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jalanPintasTitle.setText("Jalan Pintas");

        shortcut1.setText("+ Tambah Dosen");
        shortcut1.setPreferredSize(new java.awt.Dimension(153, 23));
        shortcut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortcut1ActionPerformed(evt);
            }
        });

        shortcut2.setText("+ Tambah Mahasiswa");
        shortcut2.setPreferredSize(new java.awt.Dimension(153, 23));
        shortcut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortcut2ActionPerformed(evt);
            }
        });

        shortcut3.setText("+ Buat Kelas");
        shortcut3.setPreferredSize(new java.awt.Dimension(153, 23));
        shortcut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortcut3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jalanPintasTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shortcut1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shortcut3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(shortcut2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addComponent(dateLabel)
                .addGap(4, 4, 4)
                .addComponent(clockLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jalanPintasTitle)
                .addGap(18, 18, 18)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shortcut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shortcut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(shortcut3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void shortcut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortcut1ActionPerformed
        // Shortcut ke panel Tambah Dosen
        switchToPanel(new AdminDosenPanel());
    }//GEN-LAST:event_shortcut1ActionPerformed

    private void shortcut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortcut2ActionPerformed
        // Shortcut ke panel Tambah Mahasiswa
        switchToPanel(new AdminMahasiswaPanel());
    }//GEN-LAST:event_shortcut2ActionPerformed

    private void shortcut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortcut3ActionPerformed
        // Shortcut ke panel Buat Kelas
        switchToPanel(new AdminKelasPanel());
    }//GEN-LAST:event_shortcut3ActionPerformed

    private void switchToPanel(javax.swing.JPanel newPanel) {
        // Cari parent container (mainPanel dari AdminHomePage)
        java.awt.Container parent = this.getParent();
        if (parent != null) {
            parent.removeAll();
            parent.add(newPanel, java.awt.BorderLayout.CENTER);
            parent.revalidate();
            parent.repaint();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockLabel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JLabel informationTitle;
    private javax.swing.JLabel jalanPintasTitle;
    private javax.swing.JLabel jumlahDosen;
    private javax.swing.JPanel jumlahDosenPanel;
    private javax.swing.JLabel jumlahDosenTitle;
    private javax.swing.JLabel jumlahKelas;
    private javax.swing.JPanel jumlahKelasPanel;
    private javax.swing.JLabel jumlahKelasTitle;
    private javax.swing.JLabel jumlahMahasiswa;
    private javax.swing.JPanel jumlahMahasiswaPanel;
    private javax.swing.JLabel jumlahMahasiswaTitle;
    private javax.swing.JButton shortcut1;
    private javax.swing.JButton shortcut2;
    private javax.swing.JButton shortcut3;
    // End of variables declaration//GEN-END:variables
}
